### ISSUE TITLE
Polish Blog page design

### ISSUE THREAD

**Issue by mimiflynn** [things-nyc/things-nyc.github.io#26]
- Make the blog pages look a little more like the homepage, with some photos of the city and a little wider layout.
- Optimize pages for sharing on Twitter by following Tweet Card Guidelines: https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary.html

**Comment by jchonig** [comment]
Closing old issue.  If we want to make blog posts sharable, it should be to relevant platforms (not X)
